name: Run Tests
on:
  push:
    branches:
      - development
      - master
      - drc_07-add-github-actions
  pull_request:
    branches:
      - development
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.6
        uses: actions/setup-python@v1
        with:
          python-version: 3.6
      - name: Run bash test script
        run: ./test/example_test_data.sh